print("Enter a : ")
a = int(input());
print("Enter b : ")
b = int(input());
print("\n\tARITHEMATIC OPERATOR")
print(a,"+",b,"=",a+b)
print(a,"-",b,"=",a-b)
print(a,"*",b,"=",a*b)
print(a,"/",b,"=",a/b)
print(a,"%",b,"=",a%b)
print(a,"//",b,"=",a//b)
print(a,"**",b,"=",a**b)
print("\n\tCOMPARISION OPERATOR")
print("a == b : ",a==b)
print("a != b : ",a!=b)
print("a >= b : ",a>=b)
print("a <= b : ",a<=b)
print("\n\tASSIGNMENT OPERATOR")
a+=2
print("a += 2 : ",a)
a-=2
print("a -= 2 : ",a)
print("\n\tBITWISE OPERATOR")
print("a & b : ",a&b)
print("a | b : ",a|b)
print("a ^ b : ",a^b)
print(" ~ a : ",~a)
print("a << 2: ",a<<2)
print("a >> 2: ",a>>2)
print("\n\tLOGICAL OPERATOR")
print("a and b : ",a and b)
print("a or b : ",a or b)
print("not (a) : ",not a)
print("\n\tIDENTITY OPERATOR")
print("a is b : ",a is b)
print("a is not b : ",a is not b)
print("\n\tMEMBERSHIP OPERATOR")
a=[2,4,5,6,7,8]
print("2 in a",2 in a)
print("9 not in a",9 not in a)